config/routes.rb
Rails.application.routes.draw do
    resources :classmates

end

app/models/classmate.rb
class Classmate < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classmates_controller.rb
class ClassmatesController < ApplicationController
  before_action :set_classmate, only: [:show, :edit, :update, :destroy]

  # GET /classmates
  # GET /classmates.json
  def index
    @classmates = Classmate.all
  end

  # GET /classmates/1
  # GET /classmates/1.json
  def show
  end

  # GET /classmates/new
  def new
    @classmate = Classmate.new
  end

  # GET /classmates/1/edit
  def edit
  end

  # POST /classmates
  # POST /classmates.json
  def create
    @classmate = Classmate.new(classmate_params)

    respond_to do |format|
      if @classmate.save
        format.html { redirect_to @classmate, notice: 'Classmate was successfully created.' }
        format.json { render :show, status: :created, location: @classmate }
      else
        format.html { render :new }
        format.json { render json: @classmate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classmates/1
  # PATCH/PUT /classmates/1.json
  def update
    respond_to do |format|
      if @classmate.update(classmate_params)
        format.html { redirect_to @classmate, notice: 'Classmate was successfully updated.' }
        format.json { render :show, status: :ok, location: @classmate }
      else
        format.html { render :edit }
        format.json { render json: @classmate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classmates/1
  # DELETE /classmates/1.json
  def destroy
    @classmate.destroy
    respond_to do |format|
      format.html { redirect_to classmates_url, notice: 'Classmate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classmate
      @classmate = Classmate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classmate_params
      params.require(:classmate).permit(:name, :school, :gender, :bike)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classmates_helper.rb
module ClassmatesHelper
end

app/views/classmates/_form.html.erb
<%= form_for(@classmate) do |f| %>
  <% if @classmate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classmate.errors.count, "error") %> prohibited this classmate from being saved:</h2>

      <ul>
      <% @classmate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "姓名" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.check_box :gender %>
  </div>
  <div class="field">
    <%= f.label :bike %><br>
    <%= f.check_box :bike %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classmates/edit.html.erb
<h1>Editing classmate</h1>

<%= render 'form' %>

<%= link_to 'Show', @classmate %> |
<%= link_to 'Back', classmates_path %>

app/views/classmates/index.html.erb
<h1>聯誼名單</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>School</th>
      <th>Gender</th>
      <th>Bike</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classmates.each do |classmate| %>
      <tr>
        <td><%= classmate.name %></td>
        <td><%= classmate.school %></td>
        <td><%= classmate.gender %></td>
        <td><%= classmate.bike %></td>
        <td><%= link_to '詳細資料', classmate %></td>
        <td><%= link_to '編輯', edit_classmate_path(classmate) %></td>
        <td><%= link_to '刪除', classmate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classmate', new_classmate_path %>

app/views/classmates/new.html.erb
<h1>New classmate</h1>

<%= render 'form' %>

<%= link_to 'Back', classmates_path %>

app/views/classmates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @classmate.name %>
</p>

<p>
  <strong>School:</strong>
  <%= @classmate.school %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @classmate.gender %>
</p>

<p>
  <strong>Bike:</strong>
  <% if  @classmate.bike %>
   有車
  <% else %>
   沒車
  <% end %>
  <%= @classmate.bike %>
</p>

<%= link_to 'Edit', edit_classmate_path(@classmate) %> |
<%= link_to 'Back', classmates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meetup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>